name: am2301
values:
- name: humidity
  range:
    min: 0
    max: 100
  resolution: 2000
  command: sdsensr -b ${bus} -a ${addr} -t f32
- name: temperature
  range:
    min: 233.15
    max: 353.15
  resolution: 2000
  command: sdsensr -b ${bus} -a ${addr} -t f32 -o 4
  addend: 273.15
device:
  bus: i2c
  id: 0x26
