name: rotenccont
values:
- name: angle
  range:
    min: 0
    max: 6.283185307
  resolution: 50
  re: ^([0-9]+)
  multiplier: 0,049087385
  addend: 0
  command: sdsensr -b ${bus} -a ${addr} -t i8
device:
  bus: i2c
  id: 0x04
